### ISSUE TITLE
Sync upload stuck at 1 of N.

### ISSUE THREAD

**Issue by zmichels** [StraboSpot/strabo-mobile#173]
Trying to upload spots collected in the field so as to archive them and not accidentally delete then. When I try to upload to a dataset, the app gets stuck while reads: 
"You are uploading spot 1 of 599"

Not sure what's not working here. I've tried on WiFi and LTE... Getting other data fine, so I don't think it's the connection.

**Comment by zmichels** [comment]
If I kill the process (after 10 min no progress), the dataset appears on StraboSpot, but says there are no features: "Sorry, No features found."
Seems nothing is actually getting uploaded.

**Comment by jessica-azgs** [comment]
@zmichels sync is working fine for me. Maybe it has to do with the number of spots you're trying to upload. We'll do more testing to try and isolate the problem.

**Comment by zmichels** [comment]
Yah gets stuck at first one. Do any of your spots you are trying with have photos? If so, do those get transferred too?

**Comment by zmichels** [comment]
![](http://i.imgur.com/gyCp38i.jpg)

**Comment by zmichels** [comment]
Just tried on one of the new iPads after downloaded data (version is 0.5.3)... Still stalls at first spot of upload.
![](http://i.imgur.com/JmPtciT.jpg)

**Comment by jasonash** [comment]
@zmichels I just did some testing and came up with similar results as you. I first created a few (5) features on the app and uploaded them to the DB with no issue. Next, I uploaded a shapefile, downloaded the spots to the app, and attempted to upload them to a new dataset. My upload also stopped at 1 and did not move even after waiting ~20 minutes. I am using version 0.5.3 on Android 4.4.4 KitKat.
![screenshot_2015-07-26-20-43-55](https://cloud.githubusercontent.com/assets/7904402/8897356/78c20ecc-33d9-11e5-8b93-92c87ce16c16.png)

**Comment by ginxwar** [comment]
Is there a shapefile you could upload that I could use to test?  That would help me to determine where the error could be.

**Comment by jasonash** [comment]
@ginxwar I have uploaded the shapefile I used for testing here:

https://github.com/StraboSpot/strabo-documents/blob/master/StillwaterPoints.zip

**Comment by jessica-azgs** [comment]
@jasonash I tested downloading the features in this file and something screwy is happening with the ids. If I do a curl command the feature ids come back properly and match the id used in the self field, however if do the same "Get all Spots for Given Dataset" request from the app and log the response immediately the ids have changed slightly from what's in the self field. For example:
- `self: http://strabospot.org/db/feature/143801753195115829` and `id: 143801753195115820` 
- `self: http://strabospot.org/db/feature/143801753175259449` and `id: 143801753175259460`
- `self: http://strabospot.org/db/feature/143801753165448928` and `id: 143801753165448930` 

I think this may have to do with the Javascript range of integral precision, which I've never dealt with before.

How are you making these ids? When spots are created with the app it's creating the ids from the datetime with random a 4 digit number appended. This is giving me a 17 digit number the ids seem to have been ok. The ids the server is creating are 18 digits.

**Comment by jasonash** [comment]
@jessica-azgs Thanks for the heads-up, you were right. There was a typo in the math for creating IDs in the shapefile parser which was resulting in IDs being an order of magnitude too large (18 digits). I have fixed this issue, and now the IDs are correctly being assigned a 17 digit value. I hope this helps.

**Comment by jessica-azgs** [comment]
@jasonash I upload the shapefile again just now and downloaded the spots with the app and I'm still getting the same problem though now the ids are just 17 digits. I see that in Javascript "Integers (numbers without a period or exponent notation) are considered accurate up to 15 digits". Maybe this is still playing a factor and we just got lucky before that self always matched the id? Not sure. Should we use a timestamp and 2 random digits appended?

**Comment by jessica-azgs** [comment]
@jasonash Or do we switch the ids to a string?

**Comment by jasonash** [comment]
@jessica-azgs I have changed the ID on the shapefile parser to be UnixTime + 4 random integers, resulting in IDs 14 digits long. Surely this should suffice? This will fall below javascript's 15 digit limit and also maintain a very likely certainty of uniqueness.

**Comment by jessica-azgs** [comment]
Ok, @zmichels, the upload is working for me now, with the change that @jasonash made server-side. Thanks @jasonash! @zmichels can you try again? I uploaded the shapefile @jasonash sent, downloaded the data to the app, modified, and the uploaded again and it worked, although uploading took forever with 1700+ points - we'll have to work on that. I was also able to view the changes I made in the map viewer at strabospot.org. 

Keep in mind that since the server is assigning IDs differently now your shapefiles will have to be uploaded again, unless @jasonash can write a script to have all the IDs in the database (and wherever else those IDs are referenced: self, group, group_members, links) changed to the 14 digit IDs. But I don't know that that is feasible.

I also changed the app so spots created in the app have a 14 digit ID as well.
