### ISSUE TITLE
Main Map Begin Nesting Locks up App

### ISSUE THREAD

**Issue by jasonash** [StraboSpot/strabo-mobile#419]
When on the main map and you click the three dot menu then Begin Continuous Nesting and close the nesting modal, the entire app locks up and is no longer responsive.

I did some testing, and this issue was introduced with commit ed4410f3afe5e9b7193206e9bcb0d46519f9c4d3 (Updated Ionic to 1.3.3).

I looked through the modal code and I can't see where it is failing. There are no errors thrown.

Maybe we need to roll back to Ionic 1.3.1?

**Comment by jessicagood** [comment]
I had to upgrade to 1.3.3 to get the ionic history stack working to fix the back button issues. I'll take a look at it too and see if there's anything I can see about fixing the issue.

**Comment by jasonash** [comment]
Fixed with commit f28daf5294a886b1ce1505d7dc0d24f05f3da04b

See https://gist.github.com/jasonash/59257fe09e716c15b67408193d99e5d9

**Comment by jessicagood** [comment]
There was still a problem with this if there is an alert inside the popover.hide() promise. Added promise to the alerts to fix this issue. See commit 77d5136d4c86018a00612b0eab3496957d1d18a1
