### ISSUE TITLE
Web Version: Editing Image Properties - BUG REPORT 

### ISSUE THREAD

**Issue by aglazner** [StraboSpot/strabo-mobile#588]
I have been trying to edit the field trip project in the web browser, which is a lot more convenient than on a mobile device. However, it seems to be throwing away many changes. I edited a lot of image captions and saved (see pic 1). However, after logging out and back in the changes have been discarded (pic 2).

Note that I originally put in image names, thinking that they would be displayed with the figure, but they aren't, so my changes are to incorporate the names into the captions.

Am I doing something wrong? I think I just wasted some hours.

<img width="1206" alt="pic 1" src="https://user-images.githubusercontent.com/25137645/64575821-841b9c80-d32a-11e9-85ec-7dbfba744ef3.png">
<img width="1206" alt="pic 2" src="https://user-images.githubusercontent.com/25137645/64575822-85e56000-d32a-11e9-92cd-4dde5c4c6fb8.png">

**Comment by jessicagood** [comment]
@jasonash On the web version if you **modify** the value for an image property (title, caption, etc) that already exists then switch the project or log out when you go back to that project the value modified is back to its original value. I can see the correct json being sent to the server in `LiveDBFactory` so there something different about how the server processes the image properties object? Other spot properties can be modified alright.

**Comment by jasonash** [comment]
@jessicagood I just logged into the web version and changed an existing image title and it seemed to work correctly. Do you have an example project that I can look at to duplicate the issue?

See here:

https://www.youtube.com/watch?v=jW7BNQHNY6c

**Comment by jasonash** [comment]
@jessicagood Never mind. I can duplicate with Allens project. I'll take a look.

**Comment by jasonash** [comment]
@jessicagood  OK, I found a small bug that was causing preexisting values to not be overwritten.

I think this is fixed now. Please verify.

Thanks,

Jason

**Comment by jessicagood** [comment]
@jasonash Still not working for me. I've tried several different projects, the website itself and the development web version and still the original value returns when coming back to the project after leaving.

**Comment by aglazner** [comment]
I just verified that it still doesn’t work. Here’s a link to a video showing my version:

https://www.dropbox.com/s/kczafkl6baibpbn/Image%20problem.mov?dl=0

On Sep 11, 2019, at 1:15 PM, Jessica Good <notifications@github.com> wrote:


@jasonash<https://github.com/jasonash> Still not working for me. I've tried several different projects, the website itself and the development web version and still the original value returns when coming back to the project after leaving.

**Comment by jasonash** [comment]
@jessicagood OK, I just pushed to production again. Can you try it now?

**Comment by aglazner** [comment]
I tried one and it worked. Will fix the rest later this aft. Thanks.

On Sep 11, 2019, at 1:41 PM, Jason Ash <notifications@github.com<mailto:notifications@github.com>> wrote:


@jessicagood<https://github.com/jessicagood> OK, I just pushed to production again. Can you try it now?

**Comment by jessicagood** [comment]
@jasonash Ok I can confirm that it works now. Thanks.
